/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAtendimentoRouteImport } from './routes/_authenticated/atendimento'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedChamadaRouteImport } from './routes/_authenticated/chamada'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedImpressaoRouteImport } from './routes/_authenticated/impressao'
import { Route as AuthenticatedPacientesRouteImport } from './routes/_authenticated/pacientes'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated/profissionais'
import { Route as AuthenticatedRecepcaoRouteImport } from './routes/_authenticated/recepcao'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedSalasRouteImport } from './routes/_authenticated/salas'
import { Route as AuthenticatedSuperadminClinicasRouteImport } from './routes/_authenticated/superadmin-clinicas'
import { Route as PainelTokenRouteImport } from './routes/painel/$token'
import { Route as TotemTokenRouteImport } from './routes/totem/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtendimentoRoute =
  AuthenticatedAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChamadaRoute = AuthenticatedChamadaRouteImport.update({
  id: '/chamada',
  path: '/chamada',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImpressaoRoute = AuthenticatedImpressaoRouteImport.update({
  id: '/impressao',
  path: '/impressao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacientesRoute = AuthenticatedPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecepcaoRoute = AuthenticatedRecepcaoRouteImport.update({
  id: '/recepcao',
  path: '/recepcao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalasRoute = AuthenticatedSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuperadminClinicasRoute =
  AuthenticatedSuperadminClinicasRouteImport.update({
    id: '/superadmin-clinicas',
    path: '/superadmin-clinicas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PainelTokenRoute = PainelTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => PainelRoute,
} as any)
const TotemTokenRoute = TotemTokenRouteImport.update({
  id: '/totem/$token',
  path: '/totem/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/auth': typeof AuthRoute
  '/manual': typeof ManualRoute
  '/painel': typeof PainelRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/chamada': typeof AuthenticatedChamadaRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/impressao': typeof AuthenticatedImpressaoRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/salas': typeof AuthenticatedSalasRoute
  '/superadmin-clinicas': typeof AuthenticatedSuperadminClinicasRoute
  '/painel/$token': typeof PainelTokenRoute
  '/totem/$token': typeof TotemTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/auth': typeof AuthRoute
  '/manual': typeof ManualRoute
  '/painel': typeof PainelRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/atendimento': typeof AuthenticatedAtendimentoRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/chamada': typeof AuthenticatedChamadaRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/impressao': typeof AuthenticatedImpressaoRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/recepcao': typeof AuthenticatedRecepcaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/salas': typeof AuthenticatedSalasRoute
  '/superadmin-clinicas': typeof AuthenticatedSuperadminClinicasRoute
  '/painel/$token': typeof PainelTokenRoute
  '/totem/$token': typeof TotemTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apresentacao': typeof ApresentacaoRoute
  '/auth': typeof AuthRoute
  '/manual': typeof ManualRoute
  '/painel': typeof PainelRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/atendimento': typeof AuthenticatedAtendimentoRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/chamada': typeof AuthenticatedChamadaRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/impressao': typeof AuthenticatedImpressaoRoute
  '/_authenticated/pacientes': typeof AuthenticatedPacientesRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRoute
  '/_authenticated/recepcao': typeof AuthenticatedRecepcaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/salas': typeof AuthenticatedSalasRoute
  '/_authenticated/superadmin-clinicas': typeof AuthenticatedSuperadminClinicasRoute
  '/painel/$token': typeof PainelTokenRoute
  '/totem/$token': typeof TotemTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apresentacao'
    | '/auth'
    | '/manual'
    | '/painel'
    | '/reset-password'
    | '/agenda'
    | '/ajuda'
    | '/atendimento'
    | '/auditoria'
    | '/chamada'
    | '/checkin'
    | '/configuracoes'
    | '/dashboard'
    | '/fila'
    | '/impressao'
    | '/pacientes'
    | '/profissionais'
    | '/recepcao'
    | '/relatorios'
    | '/salas'
    | '/superadmin-clinicas'
    | '/painel/$token'
    | '/totem/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apresentacao'
    | '/auth'
    | '/manual'
    | '/painel'
    | '/reset-password'
    | '/agenda'
    | '/ajuda'
    | '/atendimento'
    | '/auditoria'
    | '/chamada'
    | '/checkin'
    | '/configuracoes'
    | '/dashboard'
    | '/fila'
    | '/impressao'
    | '/pacientes'
    | '/profissionais'
    | '/recepcao'
    | '/relatorios'
    | '/salas'
    | '/superadmin-clinicas'
    | '/painel/$token'
    | '/totem/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apresentacao'
    | '/auth'
    | '/manual'
    | '/painel'
    | '/reset-password'
    | '/_authenticated/agenda'
    | '/_authenticated/ajuda'
    | '/_authenticated/atendimento'
    | '/_authenticated/auditoria'
    | '/_authenticated/chamada'
    | '/_authenticated/checkin'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/fila'
    | '/_authenticated/impressao'
    | '/_authenticated/pacientes'
    | '/_authenticated/profissionais'
    | '/_authenticated/recepcao'
    | '/_authenticated/relatorios'
    | '/_authenticated/salas'
    | '/_authenticated/superadmin-clinicas'
    | '/painel/$token'
    | '/totem/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApresentacaoRoute: typeof ApresentacaoRoute
  AuthRoute: typeof AuthRoute
  ManualRoute: typeof ManualRoute
  PainelRoute: typeof PainelRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  TotemTokenRoute: typeof TotemTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atendimento': {
      id: '/_authenticated/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AuthenticatedAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamada': {
      id: '/_authenticated/chamada'
      path: '/chamada'
      fullPath: '/chamada'
      preLoaderRoute: typeof AuthenticatedChamadaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impressao': {
      id: '/_authenticated/impressao'
      path: '/impressao'
      fullPath: '/impressao'
      preLoaderRoute: typeof AuthenticatedImpressaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes': {
      id: '/_authenticated/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AuthenticatedPacientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recepcao': {
      id: '/_authenticated/recepcao'
      path: '/recepcao'
      fullPath: '/recepcao'
      preLoaderRoute: typeof AuthenticatedRecepcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salas': {
      id: '/_authenticated/salas'
      path: '/salas'
      fullPath: '/salas'
      preLoaderRoute: typeof AuthenticatedSalasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/superadmin-clinicas': {
      id: '/_authenticated/superadmin-clinicas'
      path: '/superadmin-clinicas'
      fullPath: '/superadmin-clinicas'
      preLoaderRoute: typeof AuthenticatedSuperadminClinicasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/painel/$token': {
      id: '/painel/$token'
      path: '/$token'
      fullPath: '/painel/$token'
      preLoaderRoute: typeof PainelTokenRouteImport
      parentRoute: typeof PainelRoute
    }
    '/totem/$token': {
      id: '/totem/$token'
      path: '/totem/$token'
      fullPath: '/totem/$token'
      preLoaderRoute: typeof TotemTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedAtendimentoRoute: typeof AuthenticatedAtendimentoRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedChamadaRoute: typeof AuthenticatedChamadaRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedImpressaoRoute: typeof AuthenticatedImpressaoRoute
  AuthenticatedPacientesRoute: typeof AuthenticatedPacientesRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRoute
  AuthenticatedRecepcaoRoute: typeof AuthenticatedRecepcaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSalasRoute: typeof AuthenticatedSalasRoute
  AuthenticatedSuperadminClinicasRoute: typeof AuthenticatedSuperadminClinicasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedAtendimentoRoute: AuthenticatedAtendimentoRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedChamadaRoute: AuthenticatedChamadaRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedImpressaoRoute: AuthenticatedImpressaoRoute,
  AuthenticatedPacientesRoute: AuthenticatedPacientesRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRoute,
  AuthenticatedRecepcaoRoute: AuthenticatedRecepcaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSalasRoute: AuthenticatedSalasRoute,
  AuthenticatedSuperadminClinicasRoute: AuthenticatedSuperadminClinicasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PainelRouteChildren {
  PainelTokenRoute: typeof PainelTokenRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelTokenRoute: PainelTokenRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApresentacaoRoute: ApresentacaoRoute,
  AuthRoute: AuthRoute,
  ManualRoute: ManualRoute,
  PainelRoute: PainelRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  TotemTokenRoute: TotemTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
